// TODO: i) currently works only in same folder:
// 		1) put out_h into same dir as in_obj.
// 		2) maybe allow to provide output dir.
// 	ii) add error handling
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <stdarg.h>
#include <unistd.h>

static char* pname;

#define TOKEN_LIST(x) 	\
	X(V ,  "v") 	\
	X(VT, "vt") 	\
	X(VN, "vn") 	\
	X(F ,  "f")	\

typedef enum {
	#define X(name, string) TOKEN_##name,
	TOKEN_LIST(X)
	#undef X
	TOKEN_UNDEFINED
} TokenKind;

TokenKind token_kind(const char* s) {
	#define X(name, str) if (strcmp(s, str) == 0) return TOKEN_##name;
	TOKEN_LIST(X)
	#undef X
	return TOKEN_UNDEFINED;
}

void die(const char *fmt, ...) {
	va_list ap;
	va_start(ap, fmt);
	if (fmt) vfprintf(stderr, fmt, ap);
	if (!fmt) fprintf(stderr, "Unknown error.\n");
	va_end(ap);

	if (fmt[0] && fmt[strlen(fmt)-1] == ':') {
		fputc(' ', stderr);
		perror(NULL);
	}

	exit(EXIT_FAILURE);
}

void counts_calculate(FILE* in_obj, size_t* v_count, size_t* vt_count, size_t* vn_count, size_t* f_count) {

	char* line = NULL;
	size_t len = 0;

	while ( getline(&line, &len, in_obj) != -1 ) {

		strtok(line, " ");
		switch (token_kind(line)) {

		case TOKEN_V:
			*v_count += 1;
			break;
		case TOKEN_VT:
			*vt_count += 1;
			break;
		case TOKEN_VN:
			*vn_count += 1;
			break;
		case TOKEN_F:
			*f_count += 1;
			break;
		}
	}

	if (*vt_count == 0 || *vn_count == 0) {
		die("Currently only textured models with triangular faces of the form\n"
		    "\t f a/b/c d/e/f g/h/i\n"
		    "are supported");
	}
}

void header_print(FILE* out_h, const char* out_name,
		size_t v_count, size_t vt_count,
		size_t vn_count, size_t f_count) {

	char type_name[512];
	char* out_name_dup = strdup(out_name);
	out_name_dup[0] = toupper(out_name_dup[0]);
	snprintf(type_name, sizeof(type_name), "%sMesh", out_name_dup);
	free(out_name_dup);

	fprintf(out_h, "// This file was generated by objToC.\n");
	fprintf(out_h, "#pragma once\n\n");

	fprintf(out_h, "#include \"../mesh_types.h\"\n\n");

	fprintf(out_h, "typedef struct {\n");
	fprintf(out_h, "\tsize_t v_count;\n");
	fprintf(out_h, "\tsize_t vt_count;\n");
	fprintf(out_h, "\tsize_t vn_count;\n");
	fprintf(out_h, "\tsize_t f_count;\n");
	fprintf(out_h, "\tV3f v[%zu];\n", v_count);
	fprintf(out_h, "\tV2f vt[%zu];\n", vt_count);
	fprintf(out_h, "\tV3f vn[%zu];\n", vn_count);
	fprintf(out_h, "\tFace f[%zu];\n", f_count);
	fprintf(out_h, "} %s;\n\n", type_name);

	fprintf(out_h, "static const %s mesh_%s = {\n", type_name, out_name);
	fprintf(out_h, "\t.v_count = %zu,\n", v_count);
	fprintf(out_h, "\t.vt_count = %zu,\n", vt_count);
	fprintf(out_h, "\t.vn_count = %zu,\n", vn_count);
	fprintf(out_h, "\t.f_count = %zu,\n", f_count);
}

void vertices_print(FILE* out_h, size_t v_count, float* v) {

	fprintf(out_h, "\t.v = {\n");

	size_t v_cur = 0;
	for (size_t i = 0; i < v_count - 1; i++) {
		fprintf(out_h, "\t\t{{ %+8.6f, %+8.6f, %+8.6f }},\n",
				v[v_cur], v[v_cur+1], v[v_cur+2]);
		v_cur += 3;
	}

	fprintf(out_h, "\t\t{{ %+8.6f, %+8.6f, %+8.6f }}\n",
			v[v_cur], v[v_cur+1], v[v_cur+2]);
	fprintf(out_h, "\t},\n");
}

void texture_coordinates_print(FILE* out_h, size_t vt_count, float* vt) {

	fprintf(out_h, "\t.vt = {\n");

	size_t vt_cur = 0;
	for (size_t i = 0; i < vt_count - 1; i++) {
		fprintf(out_h, "\t\t{{ %+8.6f, %+8.6f }},\n",
				vt[vt_cur], vt[vt_cur+1]);
		vt_cur += 2;
	}

	fprintf(out_h, "\t\t{{ %+8.6f, %+8.6f }}\n",
			vt[vt_cur], vt[vt_cur+1]);
	fprintf(out_h, "\t},\n");
}

void vertex_normals_print(FILE* out_h, size_t vn_count, float* vn) {

	fprintf(out_h, "\t.vn = {\n");

	size_t vn_cur = 0;
	for (size_t i = 0; i < vn_count - 1; i++) {
		fprintf(out_h, "\t\t{{ %+8.6f, %+8.6f, %+8.6f }},\n",
				vn[vn_cur], vn[vn_cur+1], vn[vn_cur+2]);
		vn_cur += 3;
	}

	fprintf(out_h, "\t\t{{ %+8.6f, %+8.6f, %+8.6f }}\n",
			vn[vn_cur], vn[vn_cur+1], vn[vn_cur+2]);
	fprintf(out_h, "\t},\n");
}

void faces_print(FILE* out_h, size_t f_count, long* f) {

	fprintf(out_h, "\t.f = {\n");

	size_t f_cur = 0;
	for (size_t i = 0; i < f_count - 1; i++) {

		fprintf(out_h, "\t\t{ .c1 = { .v = %4ld, .vt = %4ld, .vn = %4ld },\n"
			       "\t\t  .c2 = { .v = %4ld, .vt = %4ld, .vn = %4ld },\n"
			       "\t\t  .c3 = { .v = %4ld, .vt = %4ld, .vn = %4ld }, },\n",
				f[f_cur+0], f[f_cur+1], f[f_cur+2],
				f[f_cur+3], f[f_cur+4], f[f_cur+5],
				f[f_cur+6], f[f_cur+7], f[f_cur+8]);
		f_cur += 9;
	}

	fprintf(out_h, "\t\t{ .c1 = { .v = %4ld, .vt = %4ld, .vn = %4ld },\n"
		       "\t\t  .c2 = { .v = %4ld, .vt = %4ld, .vn = %4ld },\n"
		       "\t\t  .c3 = { .v = %4ld, .vt = %4ld, .vn = %4ld }, }\n",
			f[f_cur+0], f[f_cur+1], f[f_cur+2],
			f[f_cur+3], f[f_cur+4], f[f_cur+5],
			f[f_cur+6], f[f_cur+7], f[f_cur+8]);
	fprintf(out_h, "\t}\n");
}

#define BUF_MAX 1024

void make_base_path(char* arg, char* base_path) {

	const char* sls = strrchr(arg, '/');
	size_t len = sls ? (size_t) (sls - arg) + 1
			 : (size_t) 0;

	memcpy(base_path, arg, len);
	base_path[len] = '\0';
}

void make_base_name(char* arg, char* base_stripped) {

	const char* sls = strrchr(arg, '/');
	const char* base = sls ? sls + 1
			       : arg;

	const char* ext = strrchr(base, '.');
	size_t base_len = ext ? (size_t) (ext - base)
		              : (size_t) strlen(base);

	memcpy(base_stripped, base, base_len);
	base_stripped[base_len] = '\0';
}

void usage() {
	die("usage: %s input.obj [-o output-file]\n", pname);
}

typedef struct {
	bool o_flg;
	char o_arg[BUF_MAX];
} Options;
Options opt = {
	.o_flg = false
};

int main(int argc, char** argv) {

	pname = argv[0];
	if (argc < 2) usage();

	size_t arg = 2;
	while (arg < argc) {
		if (strncmp(argv[arg++], "-o", 2) == 0) {
			opt.o_flg = true;
			strcpy(opt.o_arg, argv[arg++]);
		}
	}

	FILE* in_obj = fopen(argv[1], "r");
	if (!in_obj) {
		perror("Error opening file");
		return EXIT_FAILURE;
	}

	char base_name[BUF_MAX];
	make_base_name(argv[1], base_name);

	char base_path[BUF_MAX];
	make_base_path(argv[1], base_path);

	char out_path[BUF_MAX];
	if (opt.o_flg) {
		if (opt.o_arg[strlen(opt.o_arg)-1] != '/') {
			snprintf(out_path, sizeof(out_path), "%s",
				 opt.o_arg);
		} else {
			snprintf(out_path, sizeof(out_path), "%smesh_%s.h",
				 opt.o_arg, base_name);
		}

	} else {
		snprintf(out_path, sizeof(out_path), "%smesh_%s.h",
			 base_path, base_name);
	}
	FILE* out_h = fopen(out_path, "w");

	// first pass: get counts
	size_t v_count  = 0;
	size_t vt_count = 0;
	size_t vn_count = 0;
	size_t f_count  = 0;
	counts_calculate(in_obj, &v_count, &vt_count, &vn_count, &f_count);

	float* v  = calloc((size_t) (3 *  v_count), (size_t) sizeof *v );
	float* vt = calloc((size_t) (3 * vt_count), (size_t) sizeof *vt);
	float* vn = calloc((size_t) (3 * vn_count), (size_t) sizeof *vn);
	long* f   = calloc((size_t) (9 *  f_count), (size_t) sizeof *f );

	rewind(in_obj);

	size_t  v_cur = 0;
	size_t vt_cur = 0;
	size_t vn_cur = 0;
	size_t  f_cur = 0;

	char* line = NULL;
	size_t len = 0;

	while ( getline(&line, &len, in_obj) != -1 ) {

		strtok(line, " ");
		switch (token_kind(line)) {

		case TOKEN_V: {
			const char* v1 = strtok(NULL, " ");
			const char* v2 = strtok(NULL, " ");
			const char* v3 = strtok(NULL, " ");

			char* endptr;
			v[v_cur++] = strtof(v1, &endptr);
			v[v_cur++] = strtof(v2, &endptr);
			v[v_cur++] = strtof(v3, &endptr);
		} break;

		case TOKEN_VT: {
			const char* v1 = strtok(NULL, " ");
			const char* v2 = strtok(NULL, " ");

			char* endptr;
			vt[vt_cur++] = strtof(v1, &endptr);
			vt[vt_cur++] = strtof(v2, &endptr);
		} break;

		case TOKEN_VN: {
			const char* v1 = strtok(NULL, " ");
			const char* v2 = strtok(NULL, " ");
			const char* v3 = strtok(NULL, " ");

			char* endptr;
			vn[vn_cur++] = strtof(v1, &endptr);
			vn[vn_cur++] = strtof(v2, &endptr);
			vn[vn_cur++] = strtof(v3, &endptr);
		} break;

		case TOKEN_F: {
			const char* v1v  = strtok(NULL, "/");
			const char* v1vt = strtok(NULL, "/");
			const char* v1vn = strtok(NULL, " ");
			const char* v2v  = strtok(NULL, "/");
			const char* v2vt = strtok(NULL, "/");
			const char* v2vn = strtok(NULL, " ");
			const char* v3v  = strtok(NULL, "/");
			const char* v3vt = strtok(NULL, "/");
			const char* v3vn = strtok(NULL, " \n");

			char* endptr;
			f[f_cur++] = strtol(v1v,  &endptr, 10);
			f[f_cur++] = strtol(v1vt, &endptr, 10);
			f[f_cur++] = strtol(v1vn, &endptr, 10);
			f[f_cur++] = strtol(v2v,  &endptr, 10);
			f[f_cur++] = strtol(v2vt, &endptr, 10);
			f[f_cur++] = strtol(v2vn, &endptr, 10);
			f[f_cur++] = strtol(v3v,  &endptr, 10);
			f[f_cur++] = strtol(v3vt, &endptr, 10);
			f[f_cur++] = strtol(v3vn, &endptr, 10);
		} break;

		}
	}

	// begin: writing the output file
	header_print(out_h, base_name, v_count, vt_count, vn_count, f_count);
	vertices_print(out_h, v_count, v);
	texture_coordinates_print(out_h, vt_count, vt);
	vertex_normals_print(out_h, vn_count, vn);
	faces_print(out_h, f_count, f);
	fprintf(out_h, "};");

	// status
	printf("%s was written with:\n"
	       "\t%zu vertices\n\t%zu texture coordinate\n\t%zu vertex normals\n\t%zu faces\n",
	       out_path, v_count, vt_count, vn_count, f_count);

	fclose(out_h);
	free(vn);
	free(vt);
	free(v);
	free(f);
	free(line);
	if (in_obj) fclose(in_obj);

	return 0;
}

