#ifndef MAP_H
#define MAP_H

#include "./mesh_types.h"
#include "./textures.h"

// this layout must match the ones in the ./assets/inc/asset_* files,
// which are generated by pngToBin.
typedef struct {
	size_t v_count;
	size_t vt_count;
	size_t vn_count;
	size_t f_count;
	const V3f* v;
	const V2f* vt;
	const V3f* vn;
	const Face* f;
} Mesh;

typedef struct {
	V3f center;
	V3f extend;
} BoundingBox;

typedef struct {
	Mesh* mesh;
	const Texture* tex;
	BoundingBox bb;
	V3f up;
	V3f right;
} Model;

typedef struct {
	Model* model;
	V3f pos;
} Entity;

typedef struct {
	size_t entity_number;
	Entity entity[50];
} Map;

#endif

