// TODO: use model up/right instead of projectile/player
#include <stdio.h>
#include <limits.h>
#include <time.h>
#include <arpa/inet.h>

#define UNIT_TEST
#include "../tools/lalg/lalg.h"

#include "../inc/camera.h"
#include "../inc/text.h"
#include "../inc/color.h"
#include "../inc/backend_sdl.h"
#include "../inc/textures.h"

//#include "../assets/inc/asset_teapot.h"
//#include "../assets/inc/asset_player.h"
//#include "../assets/inc/asset_zylinder.h"
//#include "../assets/inc/asset_zaubererhut.h"
#include "../inc/meshes/mesh_lok.h"
#include "../inc/meshes/mesh_messa.h"
//#include "../assets/inc/asset_kochmuetze.h"

#define XMIN 40
#define YMIN 40
#define XMAX (SCREEN_WIDTH  - 40)
#define YMAX (SCREEN_HEIGHT - 40)

static float rot2;

typedef struct {
	V3f center;
	V3f extend;
} BoundingBox;

// this layout must match the ones in the ./assets/inc/asset_* files,
// which are generated by pngToBin.
typedef struct {
	size_t v_count;
	size_t vt_count;
	size_t vn_count;
	size_t f_count;
	const V3f* v;
	const V2f* vt;
	const V3f* vn;
	const Face* f;
} Mesh;

typedef struct {
	V3f pos;
	V3f vel;
	V3f acc;
	V3f right;
	V3f up;
	bool active;
} Projectile;
Projectile projectile = {};

typedef struct {
	Mesh* mesh;
	const Texture* tex;
	BoundingBox bb;
	V3f up;
	V3f right;
} Model;

Model model_assemble(const void* asset, const Texture* asset_texture) {

	const uint8_t* a = (const uint8_t*) asset;
	Mesh* mesh = calloc((size_t) 1, sizeof *mesh);

	// copy counts to model and set pointers to correct mesh data
	size_t offset = 0;
	memcpy(&mesh->v_count, a + offset, sizeof mesh->v_count);
	offset += sizeof mesh->v_count;
	memcpy(&mesh->vt_count, a + offset, sizeof mesh->vt_count);
	offset += sizeof mesh->vt_count;
	memcpy(&mesh->vn_count, a + offset, sizeof mesh->vn_count);
	offset += sizeof mesh->vn_count;
	memcpy(&mesh->f_count, a + offset, sizeof mesh->f_count);
	offset += sizeof mesh->f_count;

	mesh->v = (const V3f*) (a + offset);
	offset += sizeof *mesh->v * mesh->v_count;
	mesh->vt = (const V2f*) (a + offset);
	offset += sizeof *mesh->vt * mesh->vt_count;
	mesh->vn = (const V3f*) (a + offset);
	offset += sizeof *mesh->vn * mesh->vn_count;
	mesh->f = (const Face*) (a + offset);
	offset += sizeof *mesh->f * mesh->f_count;

	Model res = {
		.mesh = mesh,
		.tex = asset_texture
	};

	// calculate initial bounding box
	float x_min = +FLT_MAX; float y_min = +FLT_MAX; float z_min = +FLT_MAX;
	float x_max = -FLT_MAX; float y_max = -FLT_MAX; float z_max = -FLT_MAX;
	for (size_t i = 0; i < res.mesh->v_count; i++) {

		float x = res.mesh->v[i].x;
		float y = res.mesh->v[i].y;
		float z = res.mesh->v[i].z;

		if (x < x_min) x_min = x;
		if (x > x_max) x_max = x;
		if (y < y_min) y_min = y;
		if (y > y_max) y_max = y;
		if (z < z_min) z_min = z;
		if (z > z_max) z_max = z;
	}

	res.bb.center = (V3f) {{ (x_min+x_max)/2.0f, (y_min+y_max)/2.0f, (z_min+z_max)/2.0f }};
	res.bb.extend = (V3f) {{ (x_max-x_min)/2.0f, (y_max-y_min)/2.0f, (z_max-z_min)/2.0f }};

	return res;
}

static const float EPS = 1e-8f;

static size_t lines_count_global	   = 0;
static size_t triangle_count_global	   = 0;
static size_t models_rejected_count_global = 0;

static float* buffer_depth = NULL;

typedef struct {
	V3f position;
	V3f forward;
} Player;
Player player = {
	.position = { .x = 0.0f, .y = 0.0f, .z = 0.0f },
	.forward  = { .x = 0.0f, .y = 0.0f, .z = 1.0f }
};

typedef struct {
	uint32_t flags;
	bool grd;
	bool wfr;
	bool bfc;
	bool vfc;
	bool hat;
	bool abb;
} State;
State state = {
	.flags = 0,
	.grd = true,
	.wfr = false,
	.bfc = false,
	.vfc = false,
	.hat = false,
	.abb = false
};

void pixel_set(int32_t x, int32_t y, uint32_t* buffer, uint32_t color) {

	if (x >= (int32_t) SCREEN_WIDTH || y >= (int32_t) SCREEN_HEIGHT) return;
	buffer[x + y * (int32_t) SCREEN_WIDTH] = color;
}

void player_info() {
	float x = player.position.x;
	float y = player.position.y;
	float z = player.position.z;

	printf("Player Info: \n");
	printf("r(x, y, z) = (%6.2f, %6.2f, %6.2f)\n", x, y, z);
}

static inline V3f world_to_view(V3f v_in, Camera c) {

	V3f res   = {0};
	V3f right = norm(cross(c.forward, c.up));

	V3f rel = {
		.x = v_in.x - c.position.x,
		.y = v_in.y - c.position.y,
		.z = v_in.z - c.position.z
	};

	res.x = rel.x * right.x     + rel.y * right.y     + rel.z * right.z;
	res.y = rel.x * c.up.x      + rel.y * c.up.y      + rel.z * c.up.z;
	res.z = rel.x * c.forward.x + rel.y * c.forward.y + rel.z * c.forward.z;

	return res;
}

V2s get_image_crd(V3f v, Camera camera) {

	const float znear = camera.znear;
	const float a = (float) SCREEN_HEIGHT / (float) SCREEN_WIDTH;
	const float f = 1.0f / tanf(0.5f * camera.fovy * (float) M_PI / 180.0f);

	float px = a * f * v.x;
	float py = f * v.y;
	float pz = fmaxf(v.z, znear);

	// perspective divide
	px /= pz;
	py /= pz;

	int32_t x_screen = (int32_t) ( (px + 1.0f) * 0.5f * (float) SCREEN_WIDTH  );
	int32_t y_screen = (int32_t) ( (1.0f - py) * 0.5f * (float) SCREEN_HEIGHT );

	// Clamp to avoid overflow of small V2s types
	if (x_screen < INT32_MIN) x_screen = INT32_MIN;
	if (x_screen > INT32_MAX) x_screen = INT32_MAX;
	if (y_screen < INT32_MIN) y_screen = INT32_MIN;
	if (y_screen > INT32_MAX) y_screen = INT32_MAX;

	return (V2s) { x_screen, y_screen };
}

// Liang–Barsky clipping.
bool clipline(int32_t *x1, int32_t *y1, int32_t *x2, int32_t *y2) {

	const float dx = (float) (*x2 - *x1);
	const float dy = (float) (*y2 - *y1);

	float p[4] = { -dx, dx, -dy, dy };
	float q[4] = { (float) *x1 - (float) XMIN, (float) XMAX - (float) *x1,
		       (float) *y1 - (float) YMIN, (float) YMAX - (float) *y1 };

	float u1 = 0.0f;
	float u2 = 1.0f;

	for (int i = 0; i < 4; ++i) {
		float pi = p[i];
		float qi = q[i];

		// handle near-parallel (pi == 0)
		if (fabs(pi) < EPS) {
			if (qi < 0.0f) return false;
		} else {
			float r = qi / pi;
			if (pi < 0.0f) {
				if (r > u1) u1 = r;
			} else {
				if (r < u2) u2 = r;
			}
			if (u1 > u2) return false;
		}
	}

	float nx1 = (float) *x1 + u1 * dx;
	float ny1 = (float) *y1 + u1 * dy;
	float nx2 = (float) *x1 + u2 * dx;
	float ny2 = (float) *y1 + u2 * dy;

	*x1 = (int32_t) llroundf(nx1);
	*y1 = (int32_t) llroundf(ny1);
	*x2 = (int32_t) llroundf(nx2);
	*y2 = (int32_t) llroundf(ny2);

	return true;
}

void line_draw(V3f p1, V3f p2, uint32_t* buffer, uint32_t color, Camera camera) {

	// change to cam basis for near-plane clipping
	p1 = world_to_view(p1, camera);
	p2 = world_to_view(p2, camera);

	if (p1.z <= camera.znear && p2.z <= camera.znear) return;

	// this implies p1.z > c.znear
	if (p1.z < camera.znear) {
		// get new p0 behind clipping plane
		p1 = intersect_z(p2, p1, camera.znear);
	}

	// this implies p0.z > c.znear
	if (p2.z < camera.znear) {
		p2 = intersect_z(p1, p2, camera.znear);
	}

	V2s start = get_image_crd(p1, camera);
	V2s end   = get_image_crd(p2, camera);

	if ( start.x < (int32_t) XMIN && end.x < (int32_t) XMIN) return;
	if ( start.y < (int32_t) YMIN && end.y < (int32_t) YMIN) return;
	if ( start.x > (int32_t) XMAX && end.x > (int32_t) XMAX) return;
	if ( start.y > (int32_t) YMAX && end.y > (int32_t) YMAX) return;

	if (!clipline(&start.x, &start.y, &end.x, &end.y)) {
		return;
	}
	lines_count_global += 1;

	int32_t dx =  abs( (int32_t) end.x - (int32_t) start.x );
	int32_t sx = (int32_t) start.x < (int32_t) end.x ? 1 : -1;

	int32_t dy = -abs( (int32_t) end.y - (int32_t) start.y );
	int32_t sy = (int32_t) start.y < (int32_t) end.y ? 1 : -1;

	int32_t err = dx + dy;
	while (1) {
		pixel_set(start.x, start.y, buffer, color);
		if (start.x == end.x && start.y == end.y) break;
		int32_t e2 = 2 * err;
		if (e2 > dy) { err += dy; start.x += sx; }
		if (e2 < dx) { err += dx; start.y += sy; }
	}
}

void grid_draw(uint32_t* buffer, Camera camera) {

	int32_t grid_const = 40;
	uint32_t color = MAGENTA;

	for (int32_t i = -grid_const; i <= grid_const; i+=1) {
		V3f p1 = { .x = (float) i, .y = 0.0f, .z = -( (float) grid_const ) };
		V3f p2 = { .x = (float) i, .y = 0.0f, .z = +( (float) grid_const ) };
		line_draw(p1, p2, buffer, color, camera);
	}

	for (int32_t i = -grid_const; i <= grid_const; i+=1) {
		V3f p1 = { .x = -( (float) grid_const ), .y = 0.0f, .z = (float) i};
		V3f p2 = { .x = +( (float) grid_const ), .y = 0.0f, .z = (float) i};
		line_draw(p1, p2, buffer, color, camera);
	}
}

void buffer_flush(uint32_t* buffer, uint32_t bytes_per_pixel) {

	memset(buffer, 0, PIXELS_NUMBER * bytes_per_pixel);
}

void background_render(uint32_t* buffer) {
	for (size_t x = XMIN; x < XMAX; x++) {
	for (size_t y = YMIN; y < YMAX; y++) {
		buffer[x + y*SCREEN_WIDTH] = 0;
	}}
}

static inline Color shade_color(Color c, float intensity) {

	if (intensity < 0.1f) intensity = 0.1f;
	if (intensity > 1.0f) intensity = 1.0f;

	uint32_t i = (uint32_t) (intensity * 255.0f);

	uint32_t r = ( (c >> 24) & 0xFF) * i >> 8;
	uint32_t g = ( (c >> 16) & 0xFF) * i >> 8;
	uint32_t b = ( (c >>  8) & 0xFF) * i >> 8;
	uint32_t a =   (c        & 0xFF)         ;

	return (r << 24) | (g << 16) | (b << 8) | a;
}

void triangle_draw(Triangle t, V2f uv1, V2f uv2, V2f uv3, uint32_t* buffer, Camera camera, Color color, const Texture* tex) {

	if (state.wfr) {
		line_draw(t.v1, t.v2, buffer, color, camera);
		line_draw(t.v1, t.v3, buffer, color, camera);
		line_draw(t.v2, t.v3, buffer, color, camera);
		return;
	}

	// change to cam basis (view space)
	t.v1 = world_to_view(t.v1, camera);
	t.v2 = world_to_view(t.v2, camera);
	t.v3 = world_to_view(t.v3, camera);

	float znear = camera.znear;
	if (t.v1.z <= znear && t.v2.z <= znear && t.v3.z <= znear) return;

	// also for lighting
	V3f n = norm(cross( sub(t.v2, t.v1), sub(t.v3, t.v1) ));
	if (state.bfc) {
		// cull backfaces
		if ( dot(t.v1, n) <= 0 ) return;
	}

	V2s v1 = get_image_crd(t.v1, camera);
	V2s v2 = get_image_crd(t.v2, camera);
	V2s v3 = get_image_crd(t.v3, camera);

	// skip triangles that are completely out of the image
	if ( v1.x < (int32_t) XMIN && v2.x < (int32_t) XMIN && v3.x < (int32_t) XMIN) return;
	if ( v1.y < (int32_t) YMIN && v2.y < (int32_t) YMIN && v3.y < (int32_t) YMIN) return;
	if ( v1.x > (int32_t) XMAX && v2.x > (int32_t) XMAX && v3.x > (int32_t) XMAX) return;
	if ( v1.y > (int32_t) YMAX && v2.y > (int32_t) YMAX && v3.y > (int32_t) YMAX) return;

	// bounding box
	int32_t x_min = v1.x;
	if (v2.x < x_min) x_min = v2.x;
	if (v3.x < x_min) x_min = v3.x;
	int32_t x_max = v1.x;
	if (v2.x > x_max) x_max = v2.x;
	if (v3.x > x_max) x_max = v3.x;
	int32_t y_min = v1.y;
	if (v2.y < y_min) y_min = v2.y;
	if (v3.y < y_min) y_min = v3.y;
	int32_t y_max = v1.y;
	if (v2.y > y_max) y_max = v2.y;
	if (v3.y > y_max) y_max = v3.y;

	// adjust bounding box to the images clipping space
	if (x_min < (int32_t) XMIN) x_min = (int32_t) XMIN;
	if (x_max > (int32_t) XMAX) x_max = (int32_t) XMAX;
	if (y_min < (int32_t) YMIN) y_min = (int32_t) YMIN;
	if (y_max > (int32_t) YMAX) y_max = (int32_t) YMAX;

	// precompute floats for screen coords
	float v1x = (float)v1.x, v1y = (float)v1.y;
	float v2x = (float)v2.x, v2y = (float)v2.y;
	float v3x = (float)v3.x, v3y = (float)v3.y;
	float iz1 = 1.0f / t.v1.z;
	float iz2 = 1.0f / t.v2.z;
	float iz3 = 1.0f / t.v3.z;

	float denom = (v2y - v3y)*(v1x - v3x) + (v3x - v2x)*(v1y - v3y);
	if (fabsf(denom) < EPS) return;

	// get shaded color for triangle based on global light pos
	/*
	V3f light_global_pos_w = { .x = 5.0f, .y = 5.0f, .z = 5.0f };
	V3f light_global_pos_v = world_to_view(light_global_pos_w, camera);
	V3f dir = norm(sub(t.v1, light_global_pos_v));
	float intensity = dot(dir, n);
	color = shade_color(color, intensity);
	*/
	float denom_inv = 1.0f / denom;
	const float BC_EPS = 1e-6f;

	uint32_t tw = tex->width;
	uint32_t th = tex->height;

	for (int32_t y = y_min; y <= y_max; ++y) {
		float py = (float) y + 0.5f;
		for (int32_t x = x_min; x <= x_max; ++x) {

			// sample at pixel center
			float px = (float) x + 0.5f;

			// barycentric coords
			float px_minus_v3x = px - v3x;
			float py_minus_v3y = py - v3y;
			float a = ( (v2y - v3y) * px_minus_v3x + (v3x - v2x) * py_minus_v3y ) * denom_inv;
			float b = ( (v3y - v1y) * px_minus_v3x + (v1x - v3x) * py_minus_v3y ) * denom_inv;
			float c = 1.0f - a - b;

			// TODO: this is a hack, we need a consistent top-left rule
			if (a < -BC_EPS || b < -BC_EPS || c < -BC_EPS) continue;

			// get z for depth buffer
			float z_inv = 1.0f / (a * iz1 + b * iz2 + c * iz3);
			if (fabsf(z_inv) < EPS) continue;
			float z = 1.0f * z_inv;

			float u_over_z = a * (uv1.x * iz1) + b * (uv2.x * iz2) + c * (uv3.x * iz3);
			float v_over_z = a * (uv1.y * iz1) + b * (uv2.y * iz2) + c * (uv3.y * iz3);

			float u = u_over_z * z_inv;
			float v = v_over_z * z_inv;

			uint32_t tx = (uint32_t) (u * (float) (tw - 1));
			uint32_t ty = (uint32_t) ((1.0f - v ) * (float) (th - 1));

			if (tx >= tw) tx = tw - 1;
			if (ty >= th) ty = th - 1;

			size_t idx = (tx + ty*tw) * 4;
			uint32_t current_pixel =
				    ((uint32_t)tex->pixels[idx + 0] << 16) |
				    ((uint32_t)tex->pixels[idx + 1] << 8)  |
				    ((uint32_t)tex->pixels[idx + 2] << 0)  |
				    ((uint32_t)tex->pixels[idx + 3] << 24);
			Color texel = current_pixel;

			idx = (size_t) x + (size_t) y * (size_t) SCREEN_WIDTH;
			if (z < buffer_depth[idx]) {
				buffer_depth[idx] = z;
				pixel_set(x, y, buffer, texel);
			}
		}
	}
    	triangle_count_global += 1;
}

void aabb_render(BoundingBox bb, uint32_t* buffer, Camera camera) {

	float min_x = sub(bb.center, bb.extend).x;
	float min_y = sub(bb.center, bb.extend).y;
	float min_z = sub(bb.center, bb.extend).z;
	float max_x = add(bb.center, bb.extend).x;
	float max_y = add(bb.center, bb.extend).y;
	float max_z = add(bb.center, bb.extend).z;

	V3f min_ground_min = { .x = min_x, .y = min_y, .z = min_z};
	V3f min_ground_max = { .x = min_x, .y = min_y, .z = max_z};
	V3f max_ground_min = { .x = max_x, .y = min_y, .z = min_z};
	V3f max_ground_max = { .x = max_x, .y = min_y, .z = max_z};

	V3f min_sky_min = { .x = min_x, .y = max_y, .z = min_z};
	V3f min_sky_max = { .x = min_x, .y = max_y, .z = max_z};
	V3f max_sky_min = { .x = max_x, .y = max_y, .z = min_z};
	V3f max_sky_max = { .x = max_x, .y = max_y, .z = max_z};

	line_draw(min_ground_min, min_ground_max, buffer, GREEN, camera);
	line_draw(min_ground_min, max_ground_min, buffer, GREEN, camera);
	line_draw(max_ground_min, max_ground_max, buffer, GREEN, camera);
	line_draw(min_ground_max, max_ground_max, buffer, GREEN, camera);

	line_draw(min_sky_min, min_sky_max, buffer, GREEN, camera);
	line_draw(min_sky_min, max_sky_min, buffer, GREEN, camera);
	line_draw(max_sky_min, max_sky_max, buffer, GREEN, camera);
	line_draw(min_sky_max, max_sky_max, buffer, GREEN, camera);

	line_draw(min_ground_min, min_sky_min, buffer, GREEN, camera);
	line_draw(min_ground_max, min_sky_max, buffer, GREEN, camera);
	line_draw(max_ground_min, max_sky_min, buffer, GREEN, camera);
	line_draw(max_ground_max, max_sky_max, buffer, GREEN, camera);
}

void model_render_advanced(Model* model, uint32_t* buffer, Camera camera,
			   V3f offset, V3f ax1, float r, V3f ax2, float r2) {

	for (size_t i = 0; i < model->mesh->f_count; i++) {
		Triangle t = {
			.v1 = add(rot_ax(rot_ax(model->mesh->v[model->mesh->f[i].c1.v-1], ax1, r), ax2, r2), offset),
			.v2 = add(rot_ax(rot_ax(model->mesh->v[model->mesh->f[i].c2.v-1], ax1, r), ax2, r2), offset),
			.v3 = add(rot_ax(rot_ax(model->mesh->v[model->mesh->f[i].c3.v-1], ax1, r), ax2, r2), offset)
		};

		V2f vt1 = model->mesh->vt[model->mesh->f[i].c1.vt-1];
		V2f vt2 = model->mesh->vt[model->mesh->f[i].c2.vt-1];
		V2f vt3 = model->mesh->vt[model->mesh->f[i].c3.vt-1];

		triangle_draw(t, vt1, vt2, vt3, buffer, camera, GREEN, model->tex);
	}

	BoundingBox new = {
		.center = add(model->bb.center, offset),
		.extend = model->bb.extend
	};
	if (state.abb) aabb_render(new, buffer, camera);
}


void model_render(Model model, uint32_t* buffer, Camera camera, V3f offset) {

	for (size_t i = 0; i < model.mesh->f_count; i++) {
		Triangle t = {
			.v1 = add(model.mesh->v[model.mesh->f[i].c1.v-1], offset),
			.v2 = add(model.mesh->v[model.mesh->f[i].c2.v-1], offset),
			.v3 = add(model.mesh->v[model.mesh->f[i].c3.v-1], offset)
		};

		V2f vt1 = model.mesh->vt[model.mesh->f[i].c1.vt-1];
		V2f vt2 = model.mesh->vt[model.mesh->f[i].c2.vt-1];
		V2f vt3 = model.mesh->vt[model.mesh->f[i].c3.vt-1];

		triangle_draw(t, vt1, vt2, vt3, buffer, camera, GREEN, model.tex);
	}
}

void time_measure_start(struct timespec* t0) {
	clock_gettime(CLOCK_MONOTONIC, t0);
}

double time_measure_end_ms(struct timespec* t1, const struct timespec* t0, size_t* samples_cur, double* t_ms_avg, double* t_ms_avg_rolling, uint32_t* buffer) {
	clock_gettime(CLOCK_MONOTONIC, t1);

	time_t sec  = t1->tv_sec  - t0->tv_sec;
	long   nsec = t1->tv_nsec - t0->tv_nsec;

	if (nsec < 0) {
		sec-=1;
		nsec += 1000000000L;
	}
	*samples_cur += 1;
	if (*samples_cur == 128) {
		*t_ms_avg = *t_ms_avg_rolling / 128.0;
		*t_ms_avg_rolling = 0;
		*samples_cur = 0;
	}

	text_render(string_format(" frame time = %.2f ms, FPS = %.2f (128 samples), "
				  "lines drawn = %zu, triangles drawn = %zu\n",
				*t_ms_avg, 1000.0 / *t_ms_avg, lines_count_global,
				triangle_count_global), 0, 0, buffer, GREEN, 2);

	return (double) sec * 1000.0 + (double) nsec / 1e6;
}

Triangle triangle_offset(Triangle t, V3f offset) {
	Triangle res = {0};

	res.v1 = add(t.v1, offset);
	res.v2 = add(t.v2, offset);
	res.v3 = add(t.v3, offset);

	return res;
}

void buffer_depth_max() {

	for (size_t i = 0; i < SCREEN_WIDTH*SCREEN_HEIGHT; i++) {
		buffer_depth[i] = FLT_MAX;
	}
}



void event_loop(SDLContext* ctx, uint32_t* buffer, Camera camera, Model* model) {

	// for fps calculation
	struct timespec t0 = {0};
	struct timespec t1 = {0};

	bool running = true;

	size_t samples_cur      = 0;
	double t_ms_avg         = 0;
	double t_ms_avg_rolling = 0;
	while (running) {

		time_measure_start(&t0);
		while (SDL_PollEvent(&ctx->event) != 0) {

			switch (ctx->event.type) {

			case SDL_KEYDOWN:
				if (ctx->event.key.keysym.sym == SDLK_ESCAPE) running = false;
				if (ctx->event.key.keysym.sym == SDLK_g) state.grd = !state.grd;
				if (ctx->event.key.keysym.sym == SDLK_w) state.wfr = !state.wfr;
				if (ctx->event.key.keysym.sym == SDLK_b) state.bfc = !state.bfc;
				if (ctx->event.key.keysym.sym == SDLK_f) state.vfc = !state.vfc;
				if (ctx->event.key.keysym.sym == SDLK_h) state.hat = !state.hat;
				if (ctx->event.key.keysym.sym == SDLK_c) state.abb = !state.abb;
				if (ctx->event.key.keysym.sym == SDLK_n) {
					rot2 = 0.0f;
					projectile.active = !projectile.active;
					projectile.pos = add(camera.position, scale(4.0f, camera.forward));
					projectile.vel = scale(0.5f, camera.forward);
					projectile.right = norm( cross(camera.forward, camera.up));
					projectile.up = (V3f) {{ 0.0f, 1.0f, 0.0f }};

				}
				break;

			case SDL_MOUSEMOTION:
				V2f rel = {
					.x = (float) ctx->event.motion.xrel,
					.y = (float) ctx->event.motion.yrel,
				};
				camera_update_mouse(&camera, rel);

			default:
				break;
			}
		}

		const Uint8* keys = SDL_GetKeyboardState(NULL);
		float mv_fac = 0.05f;
		float mv_fac_player = 0.05f;

		if (keys[SDL_SCANCODE_E]) {
			camera.position = add(camera.position, scale(mv_fac, camera.forward));
		}
		if (keys[SDL_SCANCODE_UP]) {
			player.position = add(player.position, scale(mv_fac_player, player.forward));
		}

		if (keys[SDL_SCANCODE_D]) {
			V3f dir = { .x = camera.forward.x, .y = 0.0f, .z = camera.forward.z };
			dir = norm(dir);
			camera.position = sub(camera.position, scale(mv_fac, dir));
		}
		if (keys[SDL_SCANCODE_DOWN]) {
			V3f dir = { .x = player.forward.x, .y = 0.0f, .z = player.forward.z };
			dir = norm(dir);
			player.position = sub(player.position, scale(mv_fac_player, dir));
		}

		if (keys[SDL_SCANCODE_S]) {
			V3f dir = norm(cross(camera.up, camera.forward));
			camera.position = add(camera.position, scale(mv_fac, dir));
		}
		if (keys[SDL_SCANCODE_LEFT]) {
			V3f up  = { .x = 0.0f, .y = 1.0f, .z = 0.0f };
			V3f dir = norm(cross(up, player.forward));
			player.position = add(player.position, scale(mv_fac_player, dir));
		}

		if (keys[SDL_SCANCODE_F]) {
			V3f dir = norm(cross(camera.forward, camera.up));
			camera.position = add(camera.position, scale(mv_fac, dir));
		}
		if (keys[SDL_SCANCODE_RIGHT]) {
			V3f up  = { .x = 0.0f, .y = 1.0f, .z = 0.0f };
			V3f dir = norm(cross(player.forward, up));
			player.position = add(player.position, scale(mv_fac_player, dir));
		}

		if (keys[SDL_SCANCODE_SPACE]) {
			V3f v = { .x = 0.0f, .y = 1.0f, .z = 0.0f };
			camera.position = add( camera.position, scale(mv_fac, v) );
		}

		if (keys[SDL_SCANCODE_LSHIFT]) {
			V3f v = { .x = 0.0f, .y = -1.0f, .z = 0.0f };
			camera.position = add( camera.position, scale(mv_fac, v) );
		}

		if (state.grd) grid_draw(buffer, camera);

		if (projectile.active) {

			rot2 += 0.01f;
			V2f n = { .x = projectile.right.x, .y = projectile.right.z };
			n = norm(n);
			float rot = atan2f(n.x, n.y);
			//rot = 0;
			//rot2 = 0;

			model_render_advanced(&model[3], buffer, camera,
					projectile.pos, projectile.up, rot, projectile.right, rot2);
			projectile.pos = add(projectile.pos, scale(0.1f, projectile.vel));
		}

		model_render_advanced(&model[4], buffer, camera,
					player.position, projectile.up, 0, projectile.right, 0);

		/*
		if (state.hat) {
			model_render(model[1], buffer, camera);
		} else {
			model_render(model[2], buffer, camera);
		}
		*/

		text_render(string_format(" w: wireframe         = %s\n", state.wfr ? "on" : "off"),
		            0,  20, buffer, GREEN, 2);
		text_render(string_format(" b: backface culling  = %s\n", state.bfc ? "on" : "off"),
			    0,  40, buffer, GREEN, 2);
		text_render(string_format(" f: frustum culling   = %s\n", state.vfc ? "on" : "off"),
			    0,  60, buffer, GREEN, 2);
		text_render(string_format(" c: show AABB         = %s\n", state.abb ? "on" : "off"),
			    0,  80, buffer, GREEN, 2);
		text_render(string_format(" g: show grid         = %s\n", state.grd ? "on" : "off"),
			    0, 100, buffer, GREEN, 2);
		text_render(string_format(" n: projectile active = %s\n", projectile.active ? "on" : "off"),
			    0, 120, buffer, GREEN, 2);

		buffer_depth_max();

		SDL_UpdateWindowSurface(ctx->window);
		buffer_flush(buffer, ctx->bytes_per_pixel);
		//background_render(buffer);

		// end time measuring
		t_ms_avg_rolling += time_measure_end_ms(&t1, &t0, &samples_cur, &t_ms_avg, &t_ms_avg_rolling, buffer);

		lines_count_global     	     = 0;
		triangle_count_global 	     = 0;
		models_rejected_count_global = 0;
		//player_info();
		//camera_info_print(camera);
	}
}

int main(void) {

	#ifdef UNIT_TEST
		if (!LALG_tests_run()) {
			fprintf(stderr, "lalg tests failed!\n");
			exit(-2);
		}
	#endif

	buffer_depth = calloc((size_t) SCREEN_WIDTH*SCREEN_HEIGHT,
			      (size_t) sizeof *buffer_depth);
	for (size_t i = 0; i < SCREEN_WIDTH*SCREEN_HEIGHT; i++) {
		buffer_depth[i] = FLT_MAX;
	}

	SDLContext* ctx = calloc((size_t) 1, (size_t) sizeof *ctx);
	context_sdl_init(ctx);

	uint32_t* buffer = ctx->surface->pixels;

	Camera camera;
	camera_default_set(&camera);

	// prepare models
	size_t model_number = 5;
	Model model[model_number] = {};
	//model[0] = model_assemble(&asset_player  , &texture_player);
	//model[1] = model_assemble(&asset_zylinder, &texture_zylinder);
	//model[2] = model_assemble(&asset_zaubererhut, &texture_zaubererhut);
	model[3] = model_assemble(&mesh_messa, &texture_messa);
	model[4] = model_assemble(&mesh_lok, &texture_lok);

	// event loop
	event_loop(ctx, buffer, camera, model);

	// clean-up
	free(model[0].mesh);
	free(model[1].mesh);
	free(model[2].mesh);
	free(model[3].mesh);
	free(model[4].mesh);
	free(buffer_depth);
	context_sdl_destroy(ctx);
	SDL_Quit();

	return 0;
}

